config/routes.rb
Rails.application.routes.draw do
  
  resources :categories do
	resources :costs
	resources :incomes
  end
  resources :costs do
	resources :categories
	resources :incomes
  end
  resources :incomes do
	resources :costs 
	resources :categories
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :costs, dependent: :destroy
has_many :incomes, dependent: :destroy
validates :name, :presence => true
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category
  validates :category_id, :presence => true
  validates :name, :presence => true
  validates :amount, :presence => true
  validates :account, :presence => true
  end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category
  validates :category_id, :presence => true
  validates :name, :presence => true
  validates :amount, :presence => true
  validates :account, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  helper_method :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
	  # @incomes = Category.incomes.create(params[:incomes])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @category = Category.find(params[:category_id])
	@cost = @category.costs.create(cost_params)
	#@cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @category, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
		format.js
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:category_id, :name, :amount, :account)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
	@category = Category.find(params[:category_id])
	@income = @category.incomes.create(income_params)
    #@income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @category, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
		format.js
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:category_id, :name, :amount, :account)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.select(:name, options_for_select([["Salary","Salary"], ["Bonus","Bonus"],  ["Investment","Investment"], ["Stocks","Stocks"], ["Savings","Savings"], ["Loans","Loans"], ["Others","Others"], ["Clothes","Clothes"], ["Donations","Donations"], ["Education","Education"], ["Entertainment","Entertainment"], ["Food", "Food"], ["Insurance","Insurance"], ["Utilities","Utilities"], ["FutureSavings","FutureSavings"], ["Misc","Misc"] ])) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Categories</h1>
<style>
table {
color: #333;
font-family: Helvetica, Arial, sans-serif;
width: 640px;
border-collapse:
collapse; border-spacing: 0;
}

td, th {
border: 1px solid transparent; 
height: 30px;
transition: all 0.3s;  
}

th {
background: #DFDFDF;  
font-weight: bold;
}

td {
background: #FAFAFA;
text-align: center;
}

/
tr:nth-child(even) td { background: #F1F1F1; }  

tr:nth-child(odd) td { background: #FEFEFE; } 

tr td:hover { background: #efefef; color: #000; } 
}
</style>
<table border="1" align="center"  border-collapse= "collapse";
border-spacing= "0";>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>
  <tbody>      
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td BGCOLOR="#00ff00"><%= link_to 'Show', category %></td>
        <td BGCOLOR="#ffff00"><%= link_to 'Edit', edit_category_path(category) %></td>
        <td BGCOLOR="#ff0000"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h2><%= link_to 'New Category', new_category_path %><h2>

<br>
Total Income = <%=Income.sum(:amount)%>$<br>
Total Cost =<%=Cost.sum(:amount)%>$<br>
Balance = <%=(Income.sum(:amount) - Cost.sum(:amount)) %>$<br>
<% if Income.sum(:amount) - Cost.sum(:amount) < 500 %>
  <font color="red">ALERT!ALERT! You are Spending too much recently. Savings are low! %><font> 
 <%else%>
 <font color="blue">NO ALERTS. Savings are sufficient. <font>
 <%end%>

app/views/categories/new.html.erb
<style type="text/css"><!--
#wrap {
  width: 400px;
  margin:0 auto;
}
#left_col {
  float:left;
  width: 200px;
}
#right_col {
  float:right;
  width: 200px;
}
--></style>
<h1>New Category</h1>

<%= render 'form' %>
<div id="wrap">
<div id="left_col"><br>
<strong>Income Category Names</strong>
<ul>
<li>Salary</li>
<li>Bonus</li>
<li>Investment</li>
<li>Stocks</li>
<li>Savings</li>
<li>Loans</li>
<li>Other</li>
</ul>
</div>
<div id="right_col"><br>
<strong>Cost Category Names</strong>
<ul>
<li>Clothes</li>
<li>Donations</li>
<li>Education</li>
<li>Entertainment</li>
<li>Food</li>
<li>Insurance</li>
<li>Utilities</li>
<li>FutureSavings</li>
<li>Misc</li>
</ul>
</div>
</div>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<% clicked = @category.name %>
<% if clicked == "Salary" || clicked == "Bonus" || clicked == "Investment" || clicked == "Stocks" || clicked == "Savings" || clicked == "Loans" || clicked == "Other"%>
<h3>Incomes</h3>
<div id="incomes">
	<%= render :partial => @category.incomes.reverse %>
</div>

<%= form_for([@category, Income.new], remote: true) do |f| %>
	<p><%= f.label :name, "New Income Name" %><br />
		<%= f.text_field :name %>
	</p>
	<p><%= f.label :amount, "New Income Amount" %><br />
		<%= f.number_field :amount %>
	</p>
	<p><%= f.label :account, "New Income Account" %><br />
		<%= f.select(:account, options_for_select([["Cash","Cash"], ["Credit","Credit"], ["Debit","Debit"], ["Other","Other"]])) %>
	</p>
	<p><%= f.submit "Add Income" %></p>
<% end %>
<% else %>
<h3>Costs</h3>
<div id="costs">
	<%= render :partial => @category.costs.reverse %>
</div>

<%= form_for([@category, Cost.new], remote: true) do |f| %>
	<p><%= f.label :name, "New Cost Name" %><br />
		<%= f.text_field :name %>
	</p>
	<p><%= f.label :amount, "New Cost Amount" %><br />
		<%= f.number_field :amount %>
	</p>
	<p><%= f.label :account, "New Cost Account" %><br />
		<%= f.select(:account, options_for_select([["Cash","Cash"], ["Credit","Credit"], ["Debit","Debit"], ["Other","Other"]])) %>
	</p>
	<p><%= f.submit "Add Cost" %></p>
<% end %>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/costs/_cost.html.erb
<%= div_for cost do %>
<p>
	<%= h(cost.name) %>
	<%= h(cost.amount) %>
	<%= h(cost.account) %>
</p>
<% end %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/create.js.erb
var new_cost = $("<%= escape_javascript(render(:partial => @cost))%>").hide();
$('#costs').prepend(new_cost);
$('#cost_<%= @cost.id %>').fadeIn('slow');
$('#new_cost')[0].reset();

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Costs</h1>
 <% total_cost = 0 %>
<style>
table {
color: #333;
font-family: Helvetica, Arial, sans-serif;
width: 640px;
border-collapse:
collapse; border-spacing: 0;
}

td, th {
border: 1px solid transparent; 
height: 30px;
transition: all 0.3s;  
}

th {
background: #DFDFDF;  
font-weight: bold;
}

td {
background: #FAFAFA;
text-align: center;
}

tr:nth-child(even) td { background: #F1F1F1; }  

tr:nth-child(odd) td { background: #FEFEFE; } 

tr td:hover { background: #efefef; color: #000; } 
}
</style>
 
<table border="1"  align="center"> 
  <thead>
    <tr>
      <th>Category</th> 
      <th>Name</th>
      <th>Amount</th>
      <th>Account</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.category.name %></td> 
        <td><%= cost.name %></td>
        <td><%= cost.amount %></td>
        <td><%= cost.account %></td>
        <td BGCOLOR="#00ff00"><%= link_to 'Show', cost %></td>
        <td BGCOLOR="#ffff00"><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td BGCOLOR="#ff0000"><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% total_cost =total_cost+ cost.amount%>

      </tr>
    <% end %>
  </tbody>
</table>
<br>
 <p align="right"><h3> Total Cost = <%= total_cost %>$ </h3></p>
 <br>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @cost.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cost.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cost.amount %>
</p>

<p>
  <strong>Account:</strong>
  <%= @cost.account %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/_income.html.erb
<%= div_for income do %>
<p>
	<%= h(income.name) %>
	<%= h(income.amount) %>
	<%= h(income.account) %>
</p>
<% end %>

app/views/incomes/create.js.erb
var new_income = $("<%= escape_javascript(render(:partial => @income))%>").hide();
$('#incomes').prepend(new_income);
$('#income_<%= @income.id %>').fadeIn('slow');
$('#new_income')[0].reset();

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incomes</h1>
<% total_income = 0 %>           <!-- add -->
<style>
table {
color: #333;
font-family: Helvetica, Arial, sans-serif;
width: 640px;
border-collapse:
collapse; border-spacing: 0;
}

td, th {
border: 1px solid transparent; 
height: 30px;
transition: all 0.3s;  
}

th {
background: #DFDFDF;  
font-weight: bold;
}

td {
background: #FAFAFA;
text-align: center;
}
tr:nth-child(even) td { background: #F1F1F1; }  

tr:nth-child(odd) td { background: #FEFEFE; } 

tr td:hover { background: #efefef; color: #000; } 
}

</style>
<table border="1" align="center">
  <thead>
    <tr BGCOLOR="00ffff">
     <th>Category</th> 
      <th>Name</th>
      <th>Amount</th>
      <th>Account</th>
      <th colspan="3">options</th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
       <td><%= income.category.name %></td> 
        <td><%= income.name %></td>
        <td><%= income.amount %></td>
        <td><%= income.account %></td>
        <td BGCOLOR="#00ff00"><%= link_to 'Show', income %></td>
        <td BGCOLOR="#ffff00"><%= link_to 'Edit', edit_income_path(income) %></td>
        <td BGCOLOR="#ff0000"><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% total_income =total_income+ income.amount%>
      </tr>
    <% end %>
  </tbody>
</table>
<p align="right"><h3> Total Inc = <%= total_income %>$ </h3></p>
 <!-- <%= link_to 'New Income', new_income_path %> -->

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @income.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @income.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Account:</strong>
  <%= @income.account %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Walet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- <style>
body {
    background-image: url("1.gif");
}
</style> -->
</head>
<body>
<div style="background-color:black">
<br>
<h1 style="text-align:center"><font color="white">Wallet</font></h1>
<br>
</div>
<%= yield %>
</body>
 <center><%=image_tag("1.jpg",:alt=>"wallet",:size=>"100") %> <center>
</html>